manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
    # Serial PR
    - name: xudongzheng
      url-base: https://github.com/xudongzheng/
  projects:
    - name: zmk
      remote: urob
      revision: main
      import: app/west.yml
    - name: zmk_serial
      remote: xudongzheng
      revision: split-serial-pr
      import: app/west.yml
  self:
    path: config
