name: Build ZMK Firmware
on:
  push:
    branches: [main] # run build on PR merge to main
  pull_request:     # run on any action on a PR
  workflow_dispatch: # manual rerun
jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
