name: Build firmware
on:
  push:
    branches: [main] # run build on PR merge to main
  pull_requests:     # run on any action on a PR
  workflow_dispatch: # manual rerun

jobs:
  build:
    uses: urob/zmk/.github/workflows/build-user-config.yml@build-with-submodules
